// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validação das variáveis de ambiente
if (!SUPABASE_URL) {
  throw new Error(
    'Variável de ambiente VITE_SUPABASE_URL não encontrada. ' +
    'Por favor, configure no arquivo .env. ' +
    'Veja o README.md para mais informações.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Variável de ambiente VITE_SUPABASE_PUBLISHABLE_KEY não encontrada. ' +
    'Por favor, configure no arquivo .env. ' +
    'Veja o README.md para mais informações.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});